---
title: "Data Analysis Project"
author: "Caroline Koutsos, Khushboo Rathore"
date: "04 April 2023"
  html_document:
    theme: cerulean
    highlight: pygments
    toc: true
    toc_float:
      collapsed: true
      smooth_scroll: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Load libraries

Loading required libraries for this analysis.

```{r echo=FALSE, message=FALSE}
library(tidyverse)
library(lubridate)
library(janitor)
library(dplyr)
```

## Load and Cleaning Data

```{r}
### LOAD AND CLEAN DATA ###

wsoccer_matchstat_2020 <- read_csv("data/ncaa_womens_soccer_matchstats_2020.csv", guess_max = 5000)
wsoccer_matchstat_2021 <- read_csv("data/ncaa_womens_soccer_matchstats_2021.csv", guess_max = 5000)
wsoccer_matchstat_2022 <- read_csv("data/ncaa_womens_soccer_matchstats_2022.csv", guess_max = 5000)

wsoccer_playerstat_2020 <- read_csv("data/ncaa_womens_soccer_playerstats_2020.csv", guess_max = 5000)
wsoccer_playerstat_2021 <- read_csv("data/ncaa_womens_soccer_playerstats_2021.csv", guess_max = 5000)
wsoccer_playerstat_2022 <- read_csv("data/ncaa_womens_soccer_playerstats_2022.csv", guess_max = 5000)


# Possible Qs:
  # Home vs Away game performances - Down to the individual athlete?
  # Play time based on statistics/performance or year?
  # Teams and players with cards, home or away games?
  # Change in performance for players over time
```


